services:
  completion-serverless-sdk:
    build: .
    volumes:
      - .:/app
    environment:
      - AGENTA_UNAUTHORIZED_EXECUTION_ALLOWED=True
    networks:
      - agenta-network
    labels:
      - "traefik.http.routers.completion-serverless-sdk.rule=PathPrefix(`/completion-serverless-sdk/`)"
      - "traefik.http.routers.completion-serverless-sdk.entrypoints=web"
      - "traefik.http.middlewares.completion-serverless-sdk-strip.stripprefix.prefixes=/completion-serverless-sdk"
      - "traefik.http.middlewares.completion-serverless-sdk-strip.stripprefix.forceslash=true"
      - "traefik.http.routers.completion-serverless-sdk.middlewares=completion-serverless-sdk-strip"
      - "traefik.http.services.completion-serverless-sdk.loadbalancer.server.port=80"
      - "traefik.http.routers.completion-serverless-sdk.service=completion-serverless-sdk"

networks:
  agenta-network:
    external: true
