version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/agenta-backend"
    schedule:
      interval: "daily"
    groups:
      security-updates:
        dependency-type: "production"
        applies-to: "security-updates"

  - package-ecosystem: "pip"
    directory: "/agenta-cli"
    schedule:
      interval: "daily"
    groups:
      security-updates:
        dependency-type: "production"
        applies-to: "security-updates"

  - package-ecosystem: "npm"
    directory: "/agenta-web"
    schedule:
      interval: "daily"
    groups:
      security-updates:
        dependency-type: "production"
        applies-to: "security-updates"

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "daily"
    groups:
      security-updates:
        dependency-type: "production"
        applies-to: "security-updates"
