version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/agenta-backend"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/agenta-cli"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/agenta-web"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "daily"
