version: 2
updates:
  - package-ecosystem: "poetry"
    directory: "/agenta-cli" # The directory where your pyproject.toml file is located
    schedule:
      interval: "daily" # Check for updates daily
