log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "web-secure"
          scheme: "https"

  web-secure:
    address: ":443"

certificatesResolvers:
  myResolver:
    acme:
      tlschallenge: true
      email: "team@agenta.ai"
      storage: "acme.json"
      httpChallenge:
        entryPoint: "web"

providers:
  docker: {}