docker_registry_url="127.0.0.1:5001"
database_url="localhost:5432"
registry="agenta-server"
backend_url_suffix="api"
tracking_enabled=true
telemetry_api_key="phc_qH8GezjMAeToR9ygdsnTH0C9c2njhO7CFqf66pTUX7H"
allow_origins="http://localhost:3000,http://localhost:3001,http://demo.agenta.ai"