services:
  completion:
    build: .
    volumes:
      - .:/app
      - ../../agenta-cli:/agenta-cli
    environment:
      - AGENTA_UNAUTHORIZED_EXECUTION_ALLOWED=True
      - AGENTA_HOST=http://host.docker.internal
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - agenta-network
    labels:
      - "traefik.http.routers.completion.rule=PathPrefix(`/services/completion/`)"
      - "traefik.http.routers.completion.entrypoints=web"
      - "traefik.http.middlewares.completion-strip.stripprefix.prefixes=/services/completion"
      - "traefik.http.middlewares.completion-strip.stripprefix.forceslash=true"
      - "traefik.http.routers.completion.middlewares=completion-strip"
      - "traefik.http.services.completion.loadbalancer.server.port=80"
      - "traefik.http.routers.completion.service=completion"

networks:
  agenta-network:
    external: true
