name: 'Check App Accessibility'
description: 'Parse logs and check if the app is running'
inputs:
  log-file:
    description: 'The path to the log file containing the serve output'
    required: true
runs:
  using: "composite"
  steps:
    - name: Parse logs and check if app is running
      id: check-app
      shell: bash
      run: |

        echo "Serve output:"
        cat ${{ inputs.log-file }}
        APP_URL=$(grep -oP 'You can access it here: \K.+' ${{ inputs.log-file }} | head -n 1)
        echo "Extracted app URL: $APP_URL"
        if [ -z "$APP_URL" ]; then
            echo "Error: Failed to extract app URL from logs."
            exit 1
        fi
        APP_URL="${APP_URL%/}/openapi.json"

        sleep 5 # Wait for the app to start

        echo "Checking if $APP_URL is accessible"
        status_code=$(curl --max-time 10 --write-out %{http_code} --silent --output /dev/null $APP_URL)
        if [ "$status_code" -ne 200 ]; then
            echo "Error: $APP_URL is not accessible"
            exit 1
        else
            echo "$APP_URL is accessible"
        fi
