[tool.poetry]
name = "agenta"
version = "0.1.0"
description = ""
authors = ["Mahmoud Mabrouk <mahmoudmabrouk.mail@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
docker = "^6.1.1"
click = "^8.1.3"
fastapi = "^0.95.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
