[tool.poetry]
name = "agenta"
version = "0.2.7"
description = "SDK for Agenta an open-source LLMOps platform."
readme = "README.md"
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Libraries"
]
project.urls = {
    "Documentation": "https://docs.agenta.ai",
    "Source": "https://github.com/agenta-ai/agenta",
    "Homepage": "https://agenta.ai"
}

[tool.poetry.dependencies]
python = "^3.9"
docker = "^6.1.1"
click = "^8.1.3"
fastapi = "^0.95.1"
toml = "^0.10.2"
questionary = "^1.10.0"
ipdb = "^0.13.13"
python-dotenv = "^1.0.0"
python-multipart = "^0.0.6"
importlib-metadata = "^6.7.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
agenta = "agenta.cli.main:cli"
