name: Execute Backend tests

on:
        pull_request:
                branches:
                        - '*'

jobs:
        test:
            runs-on: ubuntu-latest

            steps:
                - name: Checkout code
                  uses: actions/checkout@v2

                - name: Build and run backend container
                  run: |
                        docker compose -f "docker-compose.yml" up -d --build

                # - name: Wait for backend to start
                #   run: |
                #     while [[ "$(wget -qO- http://localhost/api/docs)" != "200 OK" ]]; do
                #       sleep 1
                #     done

                - name: Run pytest in backend container
                  run: |
                      docker exec agenta-backend-1 pytest
