name: black-check-action
on:
  pull_request:
    paths:
      - "agenta-backend/**"
      - "agenta-cli/**"
      - "examples/**"

jobs:
  linter_name:
    name: runner / black check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Black
        run: pip install black
      - name: Black check
        run: |
          find . -type f -name "*.py" \
            -not -path "./agenta-backend/agenta_backend/services/selectors.py" \
            -exec black {} \;