name: Bump versions

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: "Bump Type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  migrate-db-schema-stage:
    name: Bump version
    continue-on-error: false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Bump versions
        run: |
          BUMP_TYPE=${{ inputs.bump-type }}
          echo "Bumping versions to $BUMP_TYPE"
          cd agenta-web
          npm version $BUMP_TYPE
          cd ..
          cd agenta-cli
          poetry version $BUMP_TYPE
          cd ..
          cd agenta-backend
          poetry version $BUMP_TYPE

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
