name: Execute Frontend tests

on: [pull_request]
env:
  OPENAI_API_KEY: ${{ secrets.NEXT_PUBLIC_OPENAI_API_KEY }}

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Set Environment Variables
        run: |
          echo "PYPI_API_TOKEN=${{ secrets.PYPI_API_TOKEN }}"
          echo "NEXT_PUBLIC_OPENAI_API_KEY=${{ env.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "PYPI_API_TOKEN=${{ secrets.PYPI_API_TOKEN }}" >> $GITHUB_ENV

