name: Execute Frontend tests

on: push

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build and run backend container
        run: |
          docker compose -f "docker-compose.yml" up -d --build
        working-directory: ${{ github.workspace }}

      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Stop server and database
        run: docker-compose -f "docker-compose.yml" down
        working-directory: ${{ github.workspace }}
