name: Run Backend tests

on: [pull_request]

jobs:
  continous_integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          echo "OPENAI_API_KEY=${{ secrets.NEXT_PUBLIC_OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Install Curl
        run: sudo apt install curl -y

      - name: Start Docker Compose
        run: OPENAI_API_KEY=${{ secrets.NEXT_PUBLIC_OPENAI_API_KEY }} ENVIRONMENT=github docker-compose -f "docker-compose.test.yml" up -d --build

      - name: Wait for services to be ready
        run: sleep 10

      - name: Check Templates Exists
        run: curl -i http://localhost/api/containers/templates/

      - name: Wait for Backend Service
        run: curl -i http://localhost/api/openapi.json

      # - name: Run tests
      #   run: docker exec agenta-backend-test pytest

      - name: Docker logs
        if: always() #
        run: docker ps -q | xargs -I {} docker logs {}

      - name: Stop Docker Compose
        run: docker-compose down
